export const CURRENCIES_SET_BASE_CURRENCY = 'CURRENCIES_SET_BASE_CURRENCY';
export const CURRENCIES_SET_QUOTE_CURRENCY = 'CURRENCIES_SET_QUOTE_CURRENCY';

export const CURRENCIES_SET_BASE_CURRENCY_VALUE = 'CURRENCIES_SET_BASE_CURRENCY_VALUE';
export const CURRENCIES_SET_QUOTE_CURRENCY_VALUE = 'CURRENCIES_SET_QUOTE_CURRENCY_VALUE';

export const CURRENCIES_GET_CONVERSION_RATES = 'CURRENCIES_GET_CONVERSION_RATES';

export const CURRENCIES_TOGGLE_IS_LOADING = 'CURRENCIES_TOGGLE_IS_LOADING';

export const CURRENCIES_GET_CONVERSION_RATES_SUCCESS = 'CURRENCIES_GET_CONVERSION_RATES_SUCCESS';
export const CURRENCIES_GET_CONVERSION_RATES_FAIL = 'CURRENCIES_GET_CONVERSION_RATES_FAIL';
export const CURRENCIES_SET_CONVERSION_RATES = 'CURRENCIES_SET_CONVERSION_RATES';
